name: Release Crypto-NodeJS

env:
  PKG_PATH: "crates/matrix-sdk-crypto-nodejs"


on:
  pull_request:
  push:
    tags:
      - matrix-sdk-crypto-nodejs-v[0-9]+.*

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            
          # - target: aarch64-apple-ios-sim
          #   os: macos-latest
          # - target: x86_64-apple-ios
          #   os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Load cache
        uses: Swatinem/rust-cache@v1

      - name: Build lib
        working-directory: ${{env.PKG_PATH}}
        run: |
          npm install
          npx napi build --platform --release --strip --target ${{ matrix.target }}
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: ${{ env.PKG_PATH }}/CHANGELOG.md
          files: ${{env.PKG_PATH}}/*.node
